# Generated by Django 3.2.8 on 2021-10-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgtable',
            name='image',
            field=models.ImageField(upload_to='images_dir/'),
        ),
        migrations.AlterField(
            model_name='imgtable',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
