# Generated by Django 3.2.8 on 2021-11-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_imgtable_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgtable',
            name='name',
        ),
    ]
