# Generated by Django 3.2.8 on 2021-11-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_imgtable_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImgTable',
            new_name='ImgTable2',
        ),
    ]
