# Generated by Django 3.2.8 on 2021-11-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_imgtable_imgtable2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImgTable2',
            new_name='ImgTable',
        ),
    ]
